name: 'Frontend - Quality Check'

on:
  pull_request:
    branches: [main]
    paths: [frontend/**]
    
defaults:
  run:
    working-directory: frontend
    
jobs:
  qualtiy-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: initialize Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install all dependency
        run: yarn install
      - name: lint all files
        run: yarn lint
      - name: run test
        run: yarn test:ci
      - name: update code-coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          working-directory: ./frontend/
          directory: ./coverage # optional
          flags: unittests # optional
          name: webapp # optional
          fail_ci_if_error: true # optional (default = false)
