name: 'workflow'

on:
  push:
    branches: [feature/reusable-workflow]

defaults:
  run:
    working-directory: frontend
    
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - run: yarn lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - run: yarn test:ci
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: frontend/coverage

  
  update-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: coverage
          path: frontend/coverage
      - name: update code-coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          working-directory: ./frontend/
          directory: ./coverage # optional
          flags: unittests # optional
          name: webapp # optional
          fail_ci_if_error: true # optional (default = false)